version: '3.8'

services:
  # Service Base de données PostgreSQL
  postgres_db:
    image: postgres:15
    container_name: postgres_data_quality
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: data_quality_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      # Exécution automatique des scripts DDL et DML à l'initialisation
      - ./sql/01_create_tables.sql:/docker-entrypoint-initdb.d/01_create_tables.sql
      - ./sql/02_insert_data.sql:/docker-entrypoint-initdb.d/02_insert_data.sql

  # Service Python Audit Data Quality
  data_quality_runner:
    build: .
    container_name: python_data_quality
    environment:
      DB_HOST: postgres_db
      DB_PORT: 5432
      DB_NAME: data_quality_db
      DB_USER: postgres
      DB_PASSWORD: postgrespassword
    depends_on:
      - postgres_db

volumes:
  pgdata: